### ISSUE TITLE
Plugin fails to load on Debian Bullseye

### ISSUE THREAD

**Issue by alekny** [dalegaard/srctvplus#3]
Upon server start I get this error message:
`failed to dlopen xxx/tf2/tf/addons/srctvplus.so error=/lib/i386-linux-gnu/libc.so.6: version 'GLIBC_2.35' not found (required by xxx/tf2/tf/addons/srctvplus.so)
Unable to load plugin "addons/srctvplus.so"`

The plugin might have been compiled on a system with a newer glibc (debian bullseye uses 2.31). So I tried compiling myself, yet got a different error message:
`failed to dlopen xxx/tf2/tf/addons/srctvplus.so error=xxx/tf2/tf/addons/srctvplus.so: undefined symbol: KeyValuesSystem
Unable to load plugin "addons/srctvplus.so"`

**Comment by dalegaard** [comment]
Hi @alekny ,

Ah yes, I'd blissfully forgotten about this lovely quirk. I've uploaded a new version compiled under Ubuntu 16.04(which I believe I used for the 1.1 release). Can you please test this version out and report back?

Thanks in advance!

Best regards,
Lasse

**Comment by alekny** [comment]
Hi, thanks for the quick reply. Using this version I now get this error again (same as when I compiled it on debian):
> failed to dlopen xxx/tf2/tf/addons/srctvplus.so error=xxx/tf2/tf/addons/srctvplus.so: undefined symbol: KeyValuesSystem Unable to load plugin "addons/srctvplus.so"

I've tested this on all of my linux servers, even removing all other plugins before, to rule out any crosstalk. The windows dll however works flawlessly.

Kind regards

**Comment by dalegaard** [comment]
Hi @alekny 

I was able to reproduce the issue, and I believe I managed to fix it by compiling under Debian Buster. Can you check the newest artifact I uploaded?

For some reason, the compiler/linker in Ubuntu 14.04 and 16.04 were requiring the `KeyValuesSystem` is an undefined type, and thus it wasn't correctly being linked at runtime. The seems to stem from the `tier1_i486.a`. Newer compilers/linkers correctly understand that the correct type is a function. I'm not sure what causes this interaction, so I'm really hoping it Just Works™ now!

Thanks in advance!

Best regards,
Lasse

**Comment by alekny** [comment]
Hi!
Yea, gcc sometimes feels like a delicate butterfly in this regard. 
This version loads and runs without issues, thank you very much for your help!

Kind regards,
Alex

**Comment by dalegaard** [comment]
Hi @alekny 

Super, I'll close this then. Thanks for reporting and helping troubleshoot the issue!

Best regards,
Lasse
